### ISSUE TITLE
vuepress-theme-reco主题咨询

### ISSUE THREAD

**Issue by qianguyihao** [irvingzhang0512/vuepress-reco-demo#1]
你好，我想搭建那种：左侧边栏显示多个文章的目录、右侧边栏显示单篇文章的目录结构。类似于你的这个网页：http://www.yeahflash.com/tools/blogs/

方便提供一下demo么？谢谢啦。

**Comment by irvingzhang0512** [comment]
这个就是 reco 的默认功能，配置 `subSidebar` 即可，可以参考[官方文档](https://vuepress-theme-reco.recoluan.com/views/1.x/sidebar.html)
